spring.application.name=inventarios
#conexion a H2 (base de datos en memoria para desarrollo)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Configuración H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#crear la DB pero si ya existen alguna tablas solo actualiza la nuevas sin borrar lo existente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#configurar el patron del log (en lugar del archivo logback-spring.xml
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
#Configurar el nivel de log (INFO)
logging.level.root=INFO
#Opcional, configurar niveles por paquetes
#logging.level.com.miapp=DEBUG
#logging.level.org.springframework=WARN
#server.port=8081
spring.main.banner-mode=off


